headers = {
    'accept': 'application/json, text/plain, */*',
    'accept-language': 'ru,ru-RU;q=0.9,en-US;q=0.8,en;q=0.7',
    'cache-control': 'no-cache',
    'origin': 'https://www.yescoin.gold',
    'referer': 'https://www.yescoin.gold/',
    'sec-ch-ua': '"Microsoft Edge";v="125", "Not:A-Brand";v="24", "Chromium";v="125", "Microsoft Edge Webview";v="125"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-platform': '"Windows"',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-site',
    'user-agent': 'Mozilla/5.0 (Wibdows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0',
    'x-requested-with': 'org.telegram.messenger',
}
